Display time in AM/PM format
Ams12/JavaDailyPrograms pull request #3
Opened 2023-06-07 10:46 UTC by Ams12

2023-06-08 11:51 UTC, waghmaresuyog approved these changes
Approve

2023-06-09 07:01 UTC, amitsahu8 requested changes

2023-06-09 07:01 UTC, amitsahu8 commented on PracticePrograms/src/SeventhJune/DisplayCurrentTime.java
> +        SimpleDateFormat formatTime = new SimpleDateFormat("hh.mm aa");
not a medium complexity code

2023-06-13 05:26 UTC, waghmaresuyog commented on PracticePrograms/src/SeventhJune/MatrixTranspose.java
> +
remove extra space

2023-06-13 06:41 UTC, amitsahu8 approved these changes

2023-06-13 06:41 UTC, merged